DROP TABLE IF EXISTS "project";

CREATE TABLE IF NOT EXISTS "project" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "image" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "slug" TEXT NOT NULL,
  "github" TEXT,
  "description" TEXT NOT NULL,
  "techno" JSONB, -- Stockage des technologies en format JSON
  
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
